# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShuangSeQiu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=20)),
                ('blue', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
